name: Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: "sccache"
  SCCACHE_GHA_ENABLED: "true"
  CARGO_INCREMENTAL: "0"

jobs:
  clippy:
    runs-on: windows-2025

    steps:
    # Setup
    - uses: actions/checkout@v4
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.9
   
   # Cache Cargo registry
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: cargo-registry-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-registry-${{ runner.os }}-

    # Cache Cargo index (for the package index itself)
    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/.package-cache
        key: cargo-index-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-index-${{ runner.os }}-

    # Checks
    - name: Run Clippy
      run: cargo clippy

  test:
    runs-on: windows-2025

    steps:
    # Setup
    - uses: actions/checkout@v4
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.9
   
   # Cache Cargo registry
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: cargo-registry-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-registry-${{ runner.os }}-

    # Cache Cargo index (for the package index itself)
    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/.package-cache
        key: cargo-index-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-index-${{ runner.os }}-

    # Checks
    - name: Run tests
      run: cargo test --verbose --workspace
